class classes:
    IDENTIFIER = 'indentifier'
    DELIMITER = 'delimiter'
    OPERATOR = 'operator'
    LITERAL = 'literal'
    COMMENT = 'comment'
    INDENT = 'indent'
    DEDENT = 'dedent'
    NEWLINE = 'newline'
    KEYWORD = 'keyword'
    BLOCK = 'block'
    STRING = 'string'
    ASSIGNMENT = 'assignment'
    INDICE = 'indice'
    CALLABLE = 'callable'
    DOC = 'doc'